plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.JaredMoodley.smartpantrymanager'
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId "com.JaredMoodley.smartpantrymanager"
        minSdk 24
        targetSdk 37
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            optimization {
                enable false
            }
        }
    }
    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation libs.activity.ktx
    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit
    implementation libs.recyclerview
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.0.4'
}